### PR TITLE
Dylan oliva branch

### PR DESCRIPTION
**Pull request by Nickolas-Duong**
Implement Trip.h and Trip.c files

### CODE REVIEW

**Comment by Nickolas-Duong** [comment]
Looks good to add to the main file

**Review by Aliuddink — APPROVED** [review]
looks good to me

**Comment by DJOlivaCPP** [comment]
I wrote the code, so I feel like it should be good for merge now

**Review by DJOlivaCPP — APPROVED** [review]
a.exe in test/trip/ is unnecessary but otherwise the merge should be good

**Pull request merged**
